
[[keyboard.bindings]]
key = "N"
mods = "Command"
command.program = "sh"
command.args = [
  "-c",
  """\
    rand() {
      x="$(head -c 1 /dev/random | xxd -p | xargs -I @ printf '%d' 0x@)"
      echo "$1 + $x" | bc
    }
    ~/.local/bin/alacritty msg create-window \
      --working-directory "$PWD" \
      --option 'font.size=15.0' \
      --option 'window.dimensions={columns=80,lines=25}' \
      --option "window.position={x=$(rand 1200),y=$(rand 100)}"
  """,
]

[[keyboard.bindings]]
key = "L"
mods = "Command"
command.program = "sh"
command.args = [
  "-c",
  """\
    if [ "$(readlink ~/.config/alacritty/colors/current.toml)" = dark.toml ] ; then
      ln -sf light.toml ~/.config/alacritty/colors/current.toml
    else
      ln -sf dark.toml ~/.config/alacritty/colors/current.toml
    fi
    ~/.local/bin/alacritty msg config "$(cat ~/.config/alacritty/colors/current.toml)"
  """,
]

[[keyboard.bindings]]
key = "H"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "Q"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "W"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "M"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "/"
mods = "Control"
chars = "\u001f"

