
[[keyboard.bindings]]
key = "N"
mods = "Command"
command.program = "sh"
command.args = [
  "-c",
  """\
    ~/.local/bin/alacritty msg create-window \
      --working-directory "$PWD" \
      --option 'window.dimensions={columns=80,lines=25}' \
      --option 'window.position={x=1400,y=300}'
  """,
]

[[keyboard.bindings]]
key = "L"
mods = "Command"
command.program = "sh"
command.args = [
  "-c",
  """\
    if [ "$(readlink ~/.config/alacritty/colors/current.toml)" = dark.toml ] ; then
      ln -sf light.toml ~/.config/alacritty/colors/current.toml
    else
      ln -sf dark.toml ~/.config/alacritty/colors/current.toml
    fi
    ~/.local/bin/alacritty msg config "$(cat ~/.config/alacritty/colors/current.toml)"
  """,
]

[[keyboard.bindings]]
key = "H"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "Q"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "W"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "M"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "/"
mods = "Control"
action = "None"

