[colors.primary]
foreground = "#c5c8c6"
background = "#1d1f21"

[colors.dim]
white = "#828482"
black = "#131415"
red = "#864343"
green = "#777c44"
blue = "#556a7d"
cyan = "#5b7d78"
magenta = "#75617b"
yellow = "#9e824c"

[colors.normal]
white = "#c5c8c6"
black = "#1d1f21"
red = "#cc6666"
green = "#b5bd68"
blue = "#81a2be"
cyan = "#8abeb7"
magenta = "#b294bb"
yellow = "#f0c674"

[colors.bright]
white = "#eaeaea"
black = "#666666"
red = "#d54e53"
green = "#b9ca4a"
blue = "#7aa6da"
cyan = "#70c0b1"
magenta = "#c397d8"
yellow = "#e7c547"
