[colors.primary]
foreground = "#ebdbb2"
# background = "#282828"
background = "#1d2021"

[colors.normal]
black = "#282828"
white = "#a89984"
red = "#cc241d"
green = "#98971a"
blue = "#458588"
cyan = "#689d6a"
magenta = "#b16286"
yellow = "#d79921"

[colors.bright]
black = "#928374"
white = "#ebdbb2"
red = "#fb4934"
green = "#b8bb26"
blue = "#83a598"
cyan = "#8ec07c"
magenta = "#d3869b"
yellow = "#fabd2f"
