[colors.primary]
foreground = "#3c3836"
background = "#fbf1c7"

[colors.normal]
black = "#fbf1c7"
white = "#7c6f64"
red = "#cc241d"
green = "#98971a"
blue = "#458588"
cyan = "#689d6a"
magenta = "#b16286"
yellow = "#d79921"

[colors.bright]
black = "#928374"
white = "#3c3836"
red = "#9d0006"
green = "#79740e"
blue = "#076678"
cyan = "#427b58"
magenta = "#8f3f71"
yellow = "#b57614"
