[colors.primary]
foreground = "#ffe7d9"
background = "#12171d"
dim_foreground = "#b1978a"

[colors.dim]
black = "#000000"
white = "#828c99"
red = "#d14955"
green = "#6e9161"
blue = "#6385eb"
cyan = "#259bc2"
magenta = "#7d61c2"
yellow = "#d9a94a"

[colors.normal]
black = "#2c2f33"
white = "#ede3d6"
red = "#ff5a55"
green = "#abeb91"
blue = "#82c1ff"
cyan = "#31d3d3"
magenta = "#b354f7"
yellow = "#fce97d"

[colors.bright]
black = "#4c555e"
white = "#ffffff"
red = "#ff9794"
green = "#c9e6be"
blue = "#baddff"
cyan = "#a9ebeb"
magenta = "#fca7e3"
yellow = "#ffffb5"
