[colors.primary]
foreground = "#12171d"
background = "#ffe7d9"
dim_foreground = "#9c8273"

[colors.dim]
black = "#ffffff"
white = "#6e7175"
red = "#ff5a55"
green = "#abeb91"
blue = "#82c1ff"
cyan = "#31d3d3"
magenta = "#b354f7"
yellow = "#edcc13"

[colors.normal]
black = "#dfe4eb"
white = "#41464d"
red = "#d14955"
green = "#6e9161"
blue = "#6385eb"
cyan = "#259bc2"
magenta = "#7d61c2"
yellow = "#d9a94a"

[colors.bright]
black = "#9ca0a6"
white = "#000000"
red = "#9c0b06"
green = "#246e0b"
blue = "#0836bf"
cyan = "#046382"
magenta = "#3f1f91"
yellow = "#a68b05"
